services:
  postgres:
    image: postgres:16-alpine
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
    ports:
      - "5432:5432"
    volumes:
      - wallet-pg-data:/var/lib/postgresql/data

volumes:
  wallet-pg-data:
